lang =
    sidebar:
        overview: "概况"
        disk: "磁盘"
        raid: "阵列"
        volume: "虚拟磁盘"
        initr: "客户端"
        setting: "系统设置"
        maintain: "维护中心"
        quickmode: "快速创建"
        login: "登录"
    diskpage:
        title: "系统资源"
        tabletitle: "磁盘"
        tabletitle1: "磁盘信息"
        tabletitle2: "磁盘状态"
        btn_format_all: "格式化"
        th_location: "位置"
        th_host: "磁盘所属"
        th_health: "健康状态"
        th_raid: "组成阵列"
        th_role: "磁盘角色"
        th_capacity: "容量"
        th_init: "格式化"
        th_slot:"槽位"
        th_raidcolor:"阵列提示颜色"
        format_warning: (location) ->
            "您确认要格式化#{location}吗？"
        format_all_warning: "您确认要格式化所有第三方硬盘吗？"
        mark_spare:"注意：橙色数字为专用热备盘"        
    raidpage:
        title: "系统资源"
        tabletitle: "阵列"
        set_disk_role_btn: "热备盘"
        create_btn: "创建"
        delete_btn: "删除"
        th_detail: "详细"
        th_name: "名称"
        th_level: "阵列级别"
        th_chunk: "条块"
        th_health: "健康状态"
        th_rqrcount: "RQR计数"
        th_rebuilding: "重建进度"
        th_cap_usage: "容量使用情况"
        detail_row:
            th_location: "位置"
            th_health: "健康状态"
            th_role: "磁盘角色"
    volumepage:
        title: "系统资源"
        tabletitle: "虚拟磁盘"
        create_btn: "创建"
        delete_btn: "删除"
        th_detail: "详细"
        th_name: "名称"
        th_health: "健康状态"
        th_capacity: "容量"
        th_capacity_new: "容量"
        th_fs: "文件系统"
        th_syn: "同步进度"
        th_precreate: "预创建"
        th_syncing_warning: (name) ->
            "虚拟卷 #{name} 正在同步，请停止所有同步或等待同步完毕后重试"
        th_precreating_warning: "正在预创建，请勿操作"
        th_store_server: "存储服务"        
        th_forward_server: "转发服务"  
        detail_row:
            th_wwn: "已映射客户端"
            th_session: "iSCSI连接状态"
        btn_enable_fs: "启用"
        btn_disable_fs: "禁用"
        btn_unavail_fs: "已被使用"
        
        btn_enable_sync: "开启"
        btn_pause_sync: "暂停"
        btn_stop_sync: "禁用"
                
        btn_stop_server: "关闭"
        btn_enable_server: "服务启用"
        btn_disable_server: "服务关闭"
        btn_precreate_fs: "预创建"
        btn_precreate_unavail: "未可用"
        btn_precreate_store: "存储服务"        
        btn_precreate_forward: "转发服务"
        btn_precreate_unfinish: "预创建未完成"
                        
        th_scan: "扫描完成"
        th_scan_safety: "扫描完成，系统正常"
        th_scan_warning: "文件系统挂载失败，请点击重启,重启后请人工介入文件系统修复"
        
        syncing: "开始同步，请等候"   
    initrpage:
        title: "系统资源"
        tabletitle: "客户端"
        create_btn: "创建"
        delete_btn: "删除"
        th_detail: "详细"
        th_wwn: "WWN"
        th_wwpn: "WWPN"
        th_iface: "网口"
        th_session: "iSCSI状态"
        th_map: "映射"
        th_unmap: "解除"
        th_link: "iSCSI连接"
        td_link: "关联"
        td_unlink: "断开"
        detail_row:
            th_name: "已映射虚拟磁盘"
        warningtips:"注意:iSCSI状态更新可能有延时"
    maintainpage:
        title: "系统维护"
        upgrade: "升级"
        upgrade_tip1: "请严格按照按升级指导，对系统进行升级，如有疑问，请联系客服人员。"
        upgrade_tip2: "升级过程中，请确保不要关闭电源。"
        upgrade_btn: "选择升级文件"
        diagnostic: "诊断信息"
        diagnostic_tip1: "诊断信息用于帮助技术人员定位系统问题。"
        diagnostic_btn: "收集诊断信息"
        message_upgrade_success: "升级文件上传成功，请重启设备进行升级。"
        reboot_and_shutdown: "重启/关机"
        reboot_and_shutdown_tip: "关闭或者重启您的设备。"
        data_recovery_tip: "数据恢复用于返回上一工作阶段"        
        btn_halt: "关机"
        btn_reboot: "重启"
        btn_sysinit: "系统初始化"
        btn_recover: "数据恢复"
        btn_scan: "文件系统扫描"        
        warning_poweroff: "关闭设备会影响当前业务，您确定要继续吗？"
        warning_reboot: "重启设备会影响当前业务，您确定要继续吗？"
        warning_sysinit: "初始化系统会删除所有数据，请慎重考虑，您确定要继续吗？(初始化后系统将自动重启，IP地址将恢复为出厂配置)"
        warning_recover: "阵列恢复，重启生效。执行成功后，损坏的阵列将恢复到正常状态。请点击<重启>重启设备"
        warning_raids_safety: "数据正常，无需恢复"        
        wait_recover: "正在数据恢复，请勿操作"
        finish_recover: "恢复完成，请手动重启"
    quickmodepage:
        title: "快速创建"
        raid: "阵列"
        chunk: "条块"
        raid_input_tip: "有效字符包括英文字母，数字，下划线(_)，字母开头，长度不能超过64"
        volume: "虚拟磁盘"
        volume_input_tip: "有效字符包括英文字母，数字，下划线(_)，字母开头，长度不能超过64"
        enable_fs: "启用文件系统"
        enable_iscsi: "iSCSI自动连接"
        create_files: "预创建"
        initr: "客户端"
        initr_input_tip: "客户端名称必须以iqn.2013-01.net.zbx.initiator:为前缀,且长度不能超过96"
        create_btn: "快速创建"
        create_error: "请选择创建阵列的磁盘"
        create_error_least: "级别5阵列最少需要3块磁盘"
    settingpage:
        title: "系统设置"
        title_iface_config: "网口设置"
        th_iface: "网口"
        th_ipaddr: "IP地址"
        th_netmask: "子网掩码"
        th_edit: "编辑"
        btn_iface_edit: "编辑"
        btn_iface_cancel: "取消"
        btn_iface_confirm: "确定"
        title_gateway_config: "网关设置"
        label_gateway: "网关地址"
        btn_config_gateway: "更改"
        title_useradmin: "用户密码设置"
        label_username: "用户名"
        label_oldpasswd: "原密码"
        label_newpasswd: "新密码"
        label_newpasswd_confirm: "新密码确认"
        tooltips_new_passwd: "密码长度不能超过32个字符"
        btn_changepasswd: "更改"
        btn_eth_bonding: "网口聚合"
        btn_eth_bonding_cancel: "取消网口聚合"
        btn_eth_bonding_warning: "设备存在客户端，请删除客户端再试"
        message_newpasswd_success: "修改密码成功"
        title_service_config: "服务器配置"
        title_service_id: "服务器ID"
        title_service_local_ip: "本机IP"
        title_service_type: "服务器类型"
        title_service_port: "监听端口"
        title_service_central_ip: "中心IP"
        title_service_central_config: "连接中心配置"
        more_config: "高级配置"
        select_central: "中心服务器"
        select_transform: "转发服务器"
        select_store_path: "存储路径"
        service_central_connect: "测试中心连接"
        service_success: "更改成功"
        iface_error: "请修改IP"
        useradmin_error: "两次输入密码相同"           
    overviewpage:
        title: "系统概况"
        more: "更多"
        disk_num: "磁盘数目"
        raid_num: "阵列数目"
        volume_num: "虚拟磁盘数目"
        initr_num: "客户端数目"
        title_load: "设备负载"
        title_cpu_load: "处理器"
        title_mem_load: "缓存"
        title_temp_load: "温度"
        title_flow: "流量"
        btn_write_flow: "写"
        btn_read_flow: "读"
        title_notice: "通知"
        tab_log: "日志"
    initr_create_modal:
        title: "创建客户端"
        wwn: "WWN"
        wwpn: "WWPN"
        portals: "Portals"
        tooltips_initr: "客户端名称必须以iqn.2013-01.net.zbx.initiator:为前缀,且长度不能超过96"
        btn_cancel: "取消"
        btn_confirm: "确定"
        create_error: "客户端名称必须以iqn.2013-01.net.zbx.initiator:为前缀,且长度不能超过96"
    volume_create_modal:
        title: "创建虚拟磁盘"
        name: "名称"
        tooltips_name: "有效字符包括英文字母，数字，下划线(_)，字母开头，长度不能超过64"
        raid: "阵列"
        capacity: "容量"
        automap: "是否自动映射"
        initr: "客户端"
        tooltips_initr: "客户端名称必须以iqn.2013-01.net.zbx.initiator:为前缀,且长度不能超过96"
        btn_cancel: "取消"
        btn_confirm: "确定"
    raid_set_disk_role_modal:
        title: "设置热备盘"
        label_role: "磁盘角色"
        role_global_spare: "全局热备盘"
        role_spare: "专用热备盘"
        label_raid: "阵列"
        btn_cancel: "取消"
        btn_confirm: "确定"
    raid_create_modal:
        title: "创建磁盘阵列"
        label_name: "名称"
        tooltips_name: "有效字符包括英文字母，数字，下划线(_)，字母开头，长度不能超过64"
        label_level: "级别"
        label_chunk: "条块"
        label_rebuild_priority: "重建优先级"
        label_sync: "是否同步"
        btn_cancel: "取消"
        btn_confirm: "确定"
        label_raid_disks: "数据磁盘"
        label_spare_disks: "热备磁盘"
        label_rebuild_priority_low: "低"
        label_rebuild_priority_middle: "中"
        label_rebuild_priority_high: "高"
    volume_map_modal:
        title: "映射虚拟磁盘"
        th_volumes: "虚拟磁盘信息"
        btn_cancel: "取消"
        btn_confirm: "确定"
    message_modal:
        btn_confirm: "确定"
        btn_reboot: "重启"
    confirm_modal:
        btn_cancel: "取消"
        btn_confirm: "确定"
    confirm_reboot_modal: 
        heading: "注意"
        btn_reboot: "重启"
        label_res: "文件系统"           
    confirm_vaildate_modal: 
        heading: "注意"
        init_passwd: "请输入确认密码"
        btn_sysinit: "系统初始化"
        btn_recover: "数据恢复"
        btn_cancel: "取消"
        btn_confirm: "确定"
    confirm_sync_modal:
        title: "同步终止"
        heading: "注意"
        message: "阵列损坏，请手动关闭volume同步"
        disable_sync: "关闭"
        disable_sync_success: "关闭成功"
        alert: "阵列损坏，请手动关闭volume同步"
        label_res: "虚拟磁盘"
        btn_cancel: "取消"
        btn_confirm: "确定"        
    initr_delete_modal:
        title: "删除客户端"
        heading: "注意"
        alert: "你确定要删除以下客户端吗?"
        label_res: "客户端"
        btn_cancel: "取消"
        btn_confirm: "确定"
    initr_unlink_modal:
        title: "断开客户端"
        heading: "注意"
        alert1: "1.请停止客户端所有读写操作"
        alert2: "2.请确认该客户端连接的是本机"
    initr_link_modal:
        title: "关联客户端"
        heading: "注意"
        alert1: "1.由于网络延时,可能出现连接失败的情况,如果连接失败,建议重试"
        alert2: "2.若Iscsi服务未启动,可能出现连接失败的情况,如果连接失败,建议重试"
    volume_delete_modal:
        title: "删除虚拟磁盘"
        heading: "注意"
        alert: "您确定要删除以下虚拟磁盘吗?"
        label_res: "虚拟磁盘"
        btn_cancel: "取消"
        btn_confirm: "确定"
    volume_unmap_modal:
        title: "解除虚拟磁盘映射"
        th_volumes: "虚拟磁盘信息"
        btn_cancel: "取消"
        btn_confirm: "确定"
    eth_bonding_modal:
        title: "配置聚合网口信息"
        ip: "IP地址"
        netmask: "子网掩码"
        mode: "聚合模式"
        btn_cancel: "取消"
        btn_confirm: "确定"
    fs_create_modal:
        title: "选择挂载目录"
        btn_cancel: "取消"
        btn_confirm: "确定"
    fs_choose_modal:
        title:"选择文件系统类型"
        filesystems: "文件系统"
        btn_cancel: "取消"
        btn_confirm: "确定"        
    raid_warning:
        no_deleted_raid: "请选择要删除的阵列"
        no_raid: "设备没有正常可用阵列，请先创建阵列或修复阵列"
    volume_warning:
        no_deleted_volume: "请选择要删除的虚拟磁盘"
        no_raid: "设备没有阵列，请先创建阵列"
        no_fs: "设备正常，无需扫描"
        unnormal_raid: "阵列错误，无法同步，请手动暂停同步。"
        
        
        volume_mapped_to_initrs: (name) ->
            "#{name} 存在映射，无法删除"
        volume_mapped_to_fs: (name) ->
            "#{name} 存在映射，无法启用文件系统"            
        fs_on_volume: (name) ->
            "#{name} 存在文件系统，无法删除"
        only_support_one_fs: "设备仅支持启用一个文件系统"
        over_max_fs: "已超过可用最大文件系统数"
        enable_fs: "您确定要启用文件系统吗？"
        disable_fs: "禁用文件系统，会删除数据，您确定要禁用吗？"
        
        enable_sync: (name) ->
            "启用全零同步会对虚拟卷进行格式化，您确定要同步虚拟卷#{name}吗？"
        disable_sync: "阵列错误，无法同步"            
        syncing_error: "同步失败，请开启服务或更新至最新版本"
                    
        scan_fs: "您确定要扫描文件系统吗？"
        scan_fs_fail: "扫描失败，请检查是否更新至最新版本或与管理员联系。"
    initr_warning:
        no_spared_volume: "没有可映射的虚拟磁盘"
        no_attached_volume: "没有任何可解除映射的虚拟磁盘"
        no_deleted_intir: "请选择要删除的客户端"
        detect_iscsi: (wwn) ->
            "#{wwn}存在iSCSI连接，无法进行映射，请先断开连接，再刷新界面"
        unmap_iscsi: (wwn) ->
            "#{wwn}存在iSCSI连接，无法解除映射，请先断开连接，再刷新界面"
        already_iscsi: (wwn) ->
            "#{wwn}存在iSCSI连接，请先断开连接，再进行下一步操作"
        intitr_has_map: (wwn) ->
            "#{wwn}存在映射，无法删除"
        intitr_has_link: "已存在iscsi连接,请先断开连接"
    initr_link_warning:
        link_finish: "iSCSI连接成功"
        link_err: "iSCSI连接失败"
        unlink_finish: "iSCSI断开成功"
        unlink_err: "iSCSI断开失败"
        confirm_link: (wwn) ->
            "你确定需要连接到#{wwn}吗?"
        undo_link: (wwn) ->
            "你确定需要断开#{wwn}吗?"
    eth_bonding_cancel_warning: "您确认要取消聚合网口吗？"
    raid_delete_modal:
        title: "删除磁盘阵列"
        heading: "注意"
        alert: "您确定要删除以下磁盘阵列吗?"
        label_res: "磁盘阵列"
        btn_cancel: "取消"
        btn_confirm: "确定"
    login:
        title: "请输入账户密码"
        label_device: "设备地址"
        label_username: "账户"
        label_passwd: "密码"
        btn_login: "登录"
        copyright: ""
        passwd_error:"密码错误或账号不存在"
        login_error: "登录失败"
        version_invalid_error: "客户端版本较低，请重新下载客户端，继续使用当前客户端可能会有不兼容问题"
        has_logged_error: (iface) ->
            "您已经使用#{iface}登录该设备"
        link_error:"连接服务器失败"
        online_error:"该用户已在线"
    adminview:
        menu_new: "新设备"
    dsuui:
        label_raid_disks: "数据磁盘"
        label_spare_disks: "热备磁盘"
    header:
        detect_machines_info: (num) ->
            "发现了#{num}台存储设备。"
        detect_new_machines_info: (num) ->
            "新发现了#{num}台存储设备"
        detect_no_machines_info: "未发现存储设备"
        detect_no_new_machine_info: "未发现新的存储设备"
        beep_need_login: "请登录后尝试"
        stop_beep_success: "静音成功"
        stop_beep_error: "静音失败，请开启服务或更新至最新版本"        
        btn_poweroff: "关机"
        btn_reboot: "重启"
    network_warning:
        config_iface: "您确定要修改网口吗？"
        config_gateway: "您确定要修改网关吗？"
    disconnect_warning:
        disconnect_message:"与设备连接已中断，请重新登录。"
    eth_bonding:
        has_iscsi: "设备存在iScSI连接，请先断开iScSI连接再尝试此操作。"
    login_by_other_warning: (user) ->
        "用户#{ user }已在其他地方登录，请注意密码安全"
###########################################################################################################

    server:
        centre: "中心服务器"
        store: "存储服务器"
        warning: "请问确定要切换服务器？"
        
    centrallogin:
        title: "登录"
        label_device: "设备地址"
        label_username: "账户"
        label_passwd: "密码"
        btn_login: "进入"
        setting: "高级设置"
        copyright: "2017 © Zexabox,Designed by Sam."
        login_error: "登录失败" 
        email_error:"该邮箱已存在,请重新输入"
        register_success:"注册成功"
        link_error:"服务器连接失败"
        location_a_error:"请选择市辖区"
        forget_email_error:"输入邮箱无效"

    centralsidebar:
        overview_server: "元数据"
        overview_store: "存储"
        monitor: "系统详情"
        store_monitor: "存储"
        server_monitor: "元数据"
        base:"系统服务"
        serverlist:"元数据"
        storelist:"存储"
        clientlist:"客户端"
        overview:"系统概况"
        warn:"系统告警"
        
    centralview:
        title1: "元数据概况"
        title2: "存储概况"
        title:"系统详情"
        more: "详情"
        remove:"解除"
        tips_detail:"查看详细信息"
        tabletitle: "存储"
        search_btn: "搜寻"
        add_btn: "添加"
        server_ip: "存储"
        detect_no_machines_info: "未发现存储设备"
        detect_no_new_machine_info: "未发现新的存储设备"
        unmonitor_tips:"您确定要取消对此设备的监控吗?"
        unmonitor_success:"解除监控成功"
    
    centralmonitor:
        title:"系统详情"
        more: "详情"
        remove:"解除"
        tips_detail:"查看详细信息"
        tabletitle: "拓扑图"
        search_btn: "搜寻"
        add_btn: "创建"
        server_ip: "存储"
        detect_no_machines_info: "未发现存储设备"
        detect_no_new_machine_info: "未发现新的存储设备"
        unmonitor_tips:"您确定要取消对此设备的监控吗?"
        unmonitor_success:"解除监控成功"
        detail_error:"获取失败"
        ip:"IP"
        tree:"拓扑图"
        detail:"详细信息"
    
    centralstoremonitor:
        title:"系统详情"
        more: "详情"
        remove:"解除"
        tips_detail:"查看详细信息"
        tabletitle: "存储"
        search_btn: "搜寻"
        add_btn: "创建"
        server_ip: "存储"
        detect_no_machines_info: "未发现存储设备"
        detect_no_new_machine_info: "未发现新的存储设备"
        unmonitor_tips:"您确定要取消对此设备的监控吗?"
        unmonitor_success:"解除监控成功"
        detail_error:"获取失败"
        ip:"IP"
        tree:"拓扑图"
        detail:"详细信息"
    
    centralservermonitor:
        title:"系统详情"
        more: "详情"
        remove:"解除"
        tips_detail:"查看详细信息"
        tabletitle: "元数据"
        search_btn: "搜寻"
        add_btn: "创建"
        server_ip: "存储"
        detect_no_machines_info: "未发现存储设备"
        detect_no_new_machine_info: "未发现新的存储设备"
        unmonitor_tips:"您确定要取消对此设备的监控吗?"
        unmonitor_success:"解除监控成功"
        ip:"IP"
    
    centraldisk:
        title: "系统详情"
        title_store:"存储监控"
        title_server:"服务器监控"
        tabletitle: "基本信息"
        tabletitle1: "磁盘信息"
        tabletitle2: "磁盘状态"
        tabletitle3: "阵列状态"
        tabletitle4: "虚拟磁盘"
        tabletitle5: "文件系统"
        tabletitle6: "客户端"
        tabletitle7: "设备负载"
        tabletitle8: "系统日志"
        clear_log:"清空日志"
        tabletitle_smart: "S.M.A.R.T"
        btn_back: "后退"
        btn_format_all: "格式化"
        th_location: "位置"
        th_host: "磁盘所属"
        th_health: "健康状态"
        th_raid: "组成阵列"
        th_role: "磁盘角色"
        th_capacity: "容量"
        th_capacity_used: "已用容量"
        th_init: "格式化"
        th_slot:"槽位"
        th_name:"名称"
        th_level:"级别"
        th_fs:"文件系统"
        th_chunk:"块大小"
        th_volume:"虚拟磁盘"
        th_wwn:"名称"
        th_iface:"网口"
        th_map:"映射"
        th_raidcolor:"阵列提示颜色"
        format_warning: (location) ->
            "您确认要格式化#{location}吗？"
        format_all_warning: "您确认要格式化所有第三方硬盘吗？"
        mark_spare:"注意：橙色数字为专用热备盘"
        no_data: "请插入磁盘"
        th_smart_id: "ID"
        th_smart_current: "当前"
        th_smart_min: "最差"   
        th_smart_threshold: "阈值"
        th_smart_value: "值"
        title_cpu_load:"处理器"
        title_cache_load:"缓存"
        title_mem_load:"内存"
        title_machine:"设备指标"
        title_flow_in:"网口流量"
        title_flow_out:"磁盘流量"
        date:"日期"
        level:"类型"
        message:"内容"
        status:"类型"
        all_info:"全部"
        mistake:"错误"
        warning:"警告"
        info:"提醒"
        clear_log_tips:"确定需要清空所有日志吗?"
        clear_log_success:"清空成功"
        
        btn_write_flow:"写"
        btn_read_flow:"读"
        
    central_master_store_modal:
        title: "存储"
        remove_btn:"删除"
        add_btn:"添加"
        th_name:"服务名称"
        th_ip:"IP地址"
        th_session:"状态"
        th_status:"健康"
        delete_error:"请选择删除的记录"
        delete_alert:"所有选择的配置记录会被删除,你确定吗?"
        btn_cancel: "取消"
        btn_confirm: "确定"
        
    central_delete_modal:
        title: "删除配置记录"
        heading: "注意"
        alert1: "所有选择的配置记录会被删除,你确定吗?"
        delete_success:"删除成功"
        btn_cancel: "取消"
        btn_confirm: "确定"
        
    central_server_modal:
        title: "系统资源"
        tabletitle1: "磁盘信息"
        tabletitle2: "磁盘状态"
        btn_format_all: "格式化"
        th_location: "位置"
        th_host: "磁盘所属"
        th_health: "健康状态"
        th_raid: "组成阵列"
        th_role: "磁盘角色"
        th_capacity: "容量"
        th_init: "格式化"
        th_slot:"槽位"
        
    central_modal:
        title:"创建"
        title_store:"扩容"
        title_node:"节点"
        btn_confirm:"确定"
        btn_cancel:"取消"
        label_ip:"ip地址"
        label_store_ip:"局域网内所有存储ip地址"
        btn_create:"一键创建"
        success:"创建成功"
        error:"创建失败,设备已存在"
        expand_success:"扩容成功"
        start_success:"开启成功"
        stop_success:"停止成功"
        choose:"请选择节点"
        fail:"配置失败"
        already_set:"错误:此项服务已配置"
        label_size:"高度"
        label_type:"类型"
        label_version:"型号"
        label_storage:"存储Ip"
        label_auto:"选择一个IP范围"
        label_manual:"自定义IP"
        label_number:"IP个数"
        label_start:"起初IP"
        label_service:"service IP"
        label_cloudstor:"cloudstor IP"
        label_master:"master IP"
        label_worker:"选择创建的IP如下所示:"
        label_node:"节点"
        label_status:"状态"
        label_func:"操作"
        step1:"请选择添加方式"
        step2:"请选择IP范围"
        step3:"请输入添加的IP,以,(逗号)隔开"
        step4:"请确认信息"
        
        step1s:"请选择添加节点"
        step2s:"请选择添加的IP"
        func_start:"启动"
        func_stop:"停止"
        btn_next:"下一步"
        btn_last:"上一步"
        ip_error:"设备已存在,请重新输入"
    central_search_modal:
        title: "添加"
        th_volumes: "存储信息"
        btn_cancel: "取消"
        btn_confirm: "确定"
        monitor_success: "监控成功"
        monitor_error: "监控失败，请联系管理员或升级到最新版本"
        
    central_server_view:
        title1: "元数据概况"
        title2: "存储概况"
        title: "系统概况"
        more: "详情"
        colony_num:"集群数目"
        machine_num:"服务器数目"
        warning_num:"告警数目"
        process_num:"监控数目"
        
        disk_num: "磁盘数目"
        raid_num: "阵列数目"
        volume_num: "虚拟磁盘数目"
        initr_num: "客户端数目"
        title_load: "流量监控"
        title_process: "进程监控"
        title_cpu_load: "处理器"
        title_cache_load: "系统空间"
        title_mem_load: "内存"
        title_notice: "管理日志"
        title_machine: "设备负载"
        title_temp_load:"温度"
        title_system_used:"系统空间"
        title_cap_used:"存储空间"
        clear_log:"清空日志"
        tab_log: "日志"
        tab_disks : "磁盘"
        disks_num: "磁盘总数"
        disks_status: "磁盘总状态"
        disks_cap: "总容量"
        disks_avail_cap: "可用容量"
        tab_raids: "阵列"
        raids_status: "阵列状态"
        raids_nums: "阵列总数"
        raids_avail_cap: "阵列可用容量"
        tab_nodes: "节点"
        nodes_status: "节点状态"
        nodes_nums: "节点数"
        nodes_cap: "总容量"
        tab_inits: "客户端"
        test: "一切正常！！！"
        title_flow_out: "磁盘流量"
        title_flow_in: "网口流量"
        
        btn_write_flow: "写"
        btn_read_flow: "读"
        
        date:"日期"
        level:"类型"
        status:"状态"
        message:"内容"
        all_info:"全部"
        mistake:"错误"
        warning:"警告"
        info:"提醒"
        clear_log_tips:"确定需要清空所有日志吗?"
        clear_log_success:"清空成功"
        clear_log_error:"无数据"
        status_normal:"良好"
        status_warning:"风险"
        status_danger:"危险"
        
        tips_cpu:"查看进程处理器使用情况"
        tips_mem:"查看进程内存使用情况"
        
    central_store_view:
        title1: "元数据概况"
        title2: "存储概况"
        title: "系统概况"
        more: "详细"
        cap_num:"集群容量"
        machine_num:"存储数目"
        warning_num:"告警数目"
        process_num:"监控数目"
        disk_num: "磁盘数目"
        raid_num: "阵列数目"
        volume_num: "虚拟磁盘数目"
        break_num: "阵列损坏数目"

        title_load: "流量监控"
        title_process: "进程监控"
        title_cap: "容量监控"
        title_store:"存储监控"
        title_machine: "设备负载"
        title_cpu_load: "处理器"
        title_cache_load: "缓存"
        title_mem_load: "内存"
        
        title_cap_total: "总容量"
        title_cap_used: "已用容量"
        title_cap_availed: "可用容量"
        
        title_cap: "容量使用情况"
        title_column_cap: "容量分布情况"
        title_raid: "阵列使用情况"
        title_notice: "管理日志"
        tab_log: "日志"
        clear_log:"清空日志"
        handle_log:"标记已读"
        tab_disks : "磁盘"
        disks_num: "磁盘总数"
        disks_status: "磁盘总状态"
        disks_cap: "总容量"
        disks_avail_cap: "可用容量"
        
        tab_raids: "阵列"
        raids_status: "阵列状态"
        raids_nums: "阵列总数"
        raids_avail_cap: "阵列可用容量"
        tab_nodes: "节点"
        nodes_status: "节点状态"
        nodes_nums: "节点数"
        nodes_cap: "总容量"
        tab_inits: "客户端"
        
        title_flow_out: "磁盘流量"
        title_flow_in: "网口流量"
        btn_write_flow: "写"
        btn_read_flow: "读"
        date:"日期"
        level:"类型"
        status:"状态"
        message:"内容"
        all_info:"全部"
        mistake:"错误"
        unhandled:"未处理"
        warning:"警告"
        info:"提醒"
        
        clear_log_tips:"确定需要清空所有日志吗?"
        clear_log_success:"清空成功"
        clear_log_error:"无数据"
        
        status_normal:"良好"
        status_warning:"风险"
        status_danger:"危险"
        
        title_mount:"挂载详情"
        mount:"文件系统名称"
        volume:"虚拟磁盘名称"
        raid:"阵列名称"
        dir:"挂载目录"
        
        mount_name:"/dev/mapper/VG--raid0-volume0"
        volume_name:"volume0"
        raid_name:"raid0"
        dir_name:"/nvr/d0"
        
        tips:"详情"
        tips_cpu:"查看进程处理器使用情况"
        tips_mem:"查看进程内存使用情况"
        
        title_webcam:"网络摄像机"
        btn_shot:"快照"
        title_shot:"快照结果"
        
    central_server_cpu_modal:
        title:"处理器"
        label_process:"进程名称"
        label_cpu:"占用比例(%)"
        btn_cancel:"取消"
        btn_confirm:"确定"
     
    central_server_cache_modal:
        title:"缓存"
        label_process:"进程名称"
        label_cache:"占用比例(%)"
        btn_cancel:"取消"
        btn_confirm:"确定"
        
    central_server_mem_modal:
        title:"内存"
        label_process:"进程名称"
        label_mem:"占用比例(%)"
        btn_cancel:"取消"
        btn_confirm:"确定"
        
    central_store_break_modal:
        title:"处理器"
        label_process:"进程名称"
        label_cpu:"占用比例(%)"
        btn_cancel:"取消"
        btn_confirm:"确定"
        
    central_store_disk_modal:
        title:"磁盘"
        label_location:"位置"
        label_health:"健康"
        label_role:"角色"
        label_cap:"容量"
        label_raid:"所属阵列"
        
        
        btn_cancel:"取消"
        btn_confirm:"确定"
    
    central_store_raid_modal:
        title:"阵列"
        label_name:"名称"
        label_level:"阵列级别"
        label_health:"健康"
        label_cap:"容量"
        label_used_cap:"已用容量"
        
        btn_cancel:"取消"
        btn_confirm:"确定"
     
    central_store_volume_modal:
        title:"虚拟磁盘"
        label_name:"名称"
        label_fs:"文件系统"
        label_health:"健康"
        label_cap:"容量"
        label_used_cap:"已用容量"
        
        btn_cancel:"取消"
        btn_confirm:"确定"
        
    central_pie_modal:
        title:"容量比例"
        btn_cancel:"取消"
        btn_confirm:"确定"
    
    central_server_detail:
        title:"服务器监控"
        tabletitle:"基本信息"
        btn_back:"返回"
        title_flot:"流量监控"
        title_cpu_load:"处理器"
        title_cache_load:"缓存"
        title_mem_load:"内存"
        
        
####################################################
    central_server_list:
        title: "基础服务"
        tabletitle:"元数据列表"
        add_btn:"创建"
        pre_btn:"预创建"
        remove_btn:"删除"
        th_name:"类型"
        th_ip:"地址"
        th_node:"节点"
        th_location:"位置"
        th_session:"状态"
        th_status:"健康"
        th_edit:"操作"
        th_func:"功能"
        th_detail:"详细"
        func_unset:"停止"
        func_set:"启动"
        func_pre:"扩容"
        func_node:"节点"
        check:"确认要检查此项服务吗?"
        start:"确认要启动此项服务吗?"
        stop:"确认要停止此项服务吗?"
        stop_success:"停止成功"
        start_success:"启动成功"
        check_error:"不支持检查"
        check_success:"检查成功"
        delete_error:"请选择删除的记录"
        pre_tips:"确定要进行预创建操作吗?"
        pre_success:"预创建成功"
        
    central_store_list:
        title: "基础服务"
        tabletitle:"存储列表"
        add_btn:"创建"
        pre_btn:"预创建"
        remove_btn:"删除"
        th_name:"类型"
        th_ip:"地址"
        th_server:"所属服务器"
        th_session:"状态"
        th_status:"健康"
        th_edit:"操作"
        th_detail:"详细"
        th_func:"功能"
        func_unset:"停止"
        func_mount:"开局"
        mount:"确认要挂载目录吗?"
        stop:"确认要停止此项服务吗?"
        stop_success:"停止成功"
        check_error:"不支持检查"
        check_success:"检查成功"
        mount_success:"挂载成功"
        delete_error:"请选择删除的记录"
        pre_tips:"确定要进行预创建操作吗?"
        pre_success:"预创建成功"
        
    central_client_list:
        title: "基础服务"
        tabletitle:"客户端列表"
        add_btn:"创建"
        pre_btn:"预创建"
        remove_btn:"删除"
        th_name:"类型"
        th_ip:"地址"
        th_session:"状态"
        th_status:"健康"
        th_edit:"操作"
        th_func:"功能"
        func_unset:"停止"
        func_start:"启动"
        check:"确认要检查此项服务吗?"
        stop:"确认要停止此项服务吗?"
        stop_success:"停止成功"
        check_error:"不支持检查"
        check_success:"检查成功"
        delete_error:"请选择删除的记录"
        pre_tips:"确定要进行预创建操作吗?"
        pre_success:"预创建成功"
        start:"确认要启动此客户端吗?"
        start_success:"启动成功"
        
    central_warning:
        title:"系统告警"
        title_max: "阈值设置"
        title_set: "阈值"
        th_type:"类型"
        th_normal:"普通阈值"
        th_bad:"严重阈值"
        th_edit:"操作"
        func_change:"修改"
        diagnostic:"诊断信息"
        email:"邮件告警"
        warning:"告警阈值"
        diagnostic_tip1:"诊断信息用于帮助技术人员定位系统问题。"
        diagnostic_tip2:"此功能将收集监控的所有设备的日志。"
        diagnostic_btn:"收集诊断信息"
        label_ip:"收集地址"
        download_success:"收集成功"
        add_btn:"创建"
        remove_btn:"删除"
        th_email:"邮件地址"
        th_email_level:"等级"
        th_email_ttl:"告警时间"
        delete_error:"请选择删除的邮件地址"
        warn_tip:"当相应指标超过设置的阈值时，系统将会提示告警信息并发送告警邮件。"
        email_tip:"设置需要告警的邮件，当设备出现故障时可第一时间得到通知。"
        
    central_manual:
        title:"手动添加"
        btn_cancel:"取消"
        btn_confirm:"确认"
        mode:"类型"
        label_ip:"IP地址"
        add_server_error:"目前只支持一台元数据"
        add_store_error:"机器已监控"
        
    central_value:
        btn_cancel:"取消"
        btn_confirm:"确认"
        label_normal:"普通阈值"
        label_bad:"严重阈值"
        success:"修改成功"
    
    central_email:
        title_add:"创建"
        title_change:"修改"
        
        label_address:"地址"
        label_level:"等级"
        label_ttl:"告警时间"
        success_change:"修改成功"
        success_add:"添加成功"
        error:"添加失败"
        delete_error:"请选择删除的邮件地址"
        delete_success:"删除成功"
        btn_cancel:"取消"
        btn_confirm:"确认"
        
    central_handle_log:
        title:"未处理告警"
        btn_cancel:"取消"
        btn_confirm:"标记已读"
        date:"日期"
        level:"类型"
        status:"状态"
        message:"内容"
        success:"处理成功"
        
    central_unmonitor:
       title:"解除"
       ip:"地址"
       status:"状态"
       type:"类型"
       btn_cancel:"取消"
       btn_confirm:"确认"
       success:"解除成功"
   
#############################################

    facepage:
        title:"人脸识别"
        get_card_error:"未连接读卡器或读卡器上无身份证"
        compare_success: (num) ->
            "识别成功,相似度:#{num}%"
        compare_error:"识别度过低，请将头像对准摄像头"
        compare_link_error:"与对比系统连接失败"
        compare_remain_error:"无剩余次数,请充值"

    register:
        title:"修改资料"
        label_id:"账号"
        label_sex:"性别"
        label_username:"用户名"
        label_email:"邮箱"
        label_tel:"电话"
        label_hotelname:"酒店名称"
        label_realname:"真实姓名"
        label_location:"酒店位置"
        label_location_detail:"详细地址"
        label_summary:"简介"
        success_change:"修改成功"
        map_error:"地图连接失败,请联网"
        address_error:"地址无效,请输入正确地址"
        btn_cancel:"取消"
        btn_confirm:"确认"
        part_map_error:"部分地址获取失败"
        old_pass_error:"旧密码错误,请重新输入"
       
    fileupload:
        btn_cancel:"取消"
        btn_confirm:"确认"
        upgrade_btn:"上传"
        upgrade:"请选择上传文件"
        upload_success:"上传成功"

    register_change_head:
        btn_cancel:"取消"
        btn_confirm:"确认"

    register_recharge:
        title:"充值中心"
        
    manager:
        map_error:"地图连接失败,请联网"
        address_error:"地址无效,请输入正确地址"
        confirm_delete:"您确认要删除改用户吗?"
        delete_success:"删除成功"
   
    precountpage:
        no_select:"请填写完整"
        time_error:"请重新选择时间"
        no_data:"无数据,请重新选择"
        search_error:"连接服务器失败"

    register_record:
        no_data:"获取身份证信息失败,请重试"
        location_a_error:"请选择市辖区"

this.lang = lang
